// Generated by scripts/build_clouds.js — do not edit by hand.
// The Clouds granular DSP module (see public/wasm/clouds-granular.manifest.json).
export const CLOUDS_WASM_URL = '/wasm/clouds-granular-026b0b04.wasm'
export const CLOUDS_WASM_SHA256 = '026b0b045e70c86f2c4848bd3a5d7bb4ee376acf7f8fdd0c6a56d599f89de60f'
export const CLOUDS_WASM_BYTES = 44979
