// Generated by scripts/build_clouds.js — do not edit by hand.
// The Clouds granular DSP module (see public/wasm/clouds-granular.manifest.json).
export const CLOUDS_WASM_URL = '/wasm/clouds-granular-cc30b53a.wasm'
export const CLOUDS_WASM_SHA256 = 'cc30b53a34d5e87b3137d3b59af05c596b09041264c490343a40a21487c19ed7'
export const CLOUDS_WASM_BYTES = 34534
