// Generated by scripts/build_ladder.js — do not edit by hand.
// The Analog lane filter DSP module (see public/wasm/ladder.manifest.json).
export const LADDER_WASM_URL = '/wasm/ladder-3a72c153.wasm'
export const LADDER_WASM_SHA256 = '3a72c153e4dae0002f67671688143ea145948a87397bd7c04bedaf7a1f11eea5'
export const LADDER_WASM_BYTES = 5237
export const LADDER_ABI_VERSION = 1
