// Generated by scripts/build_macro.js — do not edit by hand.
// The Macro DSP module (see public/wasm/macro.manifest.json).
export const MACRO_WASM_URL = '/wasm/macro-ed63b582.wasm'
export const MACRO_WASM_SHA256 = 'ed63b582f28f58d20de1d15ffe207dbf86cb2c808f64e7d51b690dda258f65da'
export const MACRO_WASM_BYTES = 208625
