// Generated by scripts/build_resonator.js — do not edit by hand.
// The Resonator DSP module (see public/wasm/resonator.manifest.json).
export const RESONATOR_WASM_URL = '/wasm/resonator-dbf437ea.wasm'
export const RESONATOR_WASM_SHA256 = 'dbf437ea53116f15351f10bb8ca2b171aba536a72b43eb492ecb5e261437e82c'
export const RESONATOR_WASM_BYTES = 65073
