// Generated by scripts/build_resonator.js — do not edit by hand.
// The Resonator DSP module (see public/wasm/resonator.manifest.json).
export const RESONATOR_WASM_URL = '/wasm/resonator-a9057a69.wasm'
export const RESONATOR_WASM_SHA256 = 'a9057a69ed9b59aff6bf3f6599f07f2198dd9ffd52ac8b022535891e549e65b2'
export const RESONATOR_WASM_BYTES = 61216
