#!/usr/bin/env node
// Write the compact per-city route index the MCP server composes against.
//
//   node scripts/build_route_index.js [--city <id>]     (default: every city)
//
// The server can't load lines.<city>.json per request — the files are 2–70 MB
// and only reachable as static assets — but composing a loop only needs each
// line's id, name and type plus two musical hints. This emits exactly that as a
// plain ES module (lib/server/routeIndex/<city>.js), which is committed and
// bundled with the server function, so nothing is fetched at runtime.
//
// Run it after `npm run preprocess:<city>` (it reads the slim file when present,
// the full file otherwise — stops are identical in both). Like slim:all, it is
// a separate step: forgetting it leaves the MCP tools on the previous route list.
import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'

const CITIES = ['budapest', 'helsinki', 'berlin', 'prague', 'newyork', 'zurich', 'warsaw']

function arg(name, fallback = null) {
  const i = process.argv.indexOf(`--${name}`)
  return i > -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback
}

const round2 = (n) => Math.round(n * 100) / 100

function indexRoute(route) {
  const demands = (route.stops ?? [])
    .map(stop => stop?.signals?.demand)
    .filter(value => typeof value === 'number' && Number.isFinite(value))
  const entry = {
    id: route.id,
    name: route.name ?? route.shortName ?? route.id,
    type: route.type,
    stopCount: route.stops?.length ?? 0,
    meanDemand: demands.length ? round2(demands.reduce((a, b) => a + b, 0) / demands.length) : null,
  }
  if (route.desc) entry.desc = route.desc
  return entry
}

function build(city) {
  const dir = path.join(process.cwd(), 'public', 'data')
  const slim = path.join(dir, `lines.${city}.slim.json`)
  const full = path.join(dir, `lines.${city}.json`)
  const source = fs.existsSync(slim) ? slim : full
  if (!fs.existsSync(source)) throw new Error(`No route data for "${city}" (looked for ${slim} and ${full})`)

  const data = JSON.parse(fs.readFileSync(source, 'utf8'))
  const routes = (data.routes ?? data).filter(route => route?.id && route?.type).map(indexRoute)

  const outDir = path.join(process.cwd(), 'lib', 'server', 'routeIndex')
  fs.mkdirSync(outDir, { recursive: true })
  const out = path.join(outDir, `${city}.js`)
  fs.writeFileSync(out, [
    `// Generated by scripts/build_route_index.js from ${path.basename(source)} — do not edit.`,
    '// Regenerate with `npm run index:routes` after preprocessing this city.',
    'export default [',
    ...routes.map(route => `  ${JSON.stringify(route)},`),
    ']',
    '',
  ].join('\n'))
  console.log(`${city}: ${routes.length} routes → ${path.relative(process.cwd(), out)} (${(fs.statSync(out).size / 1024).toFixed(0)} KB)`)
}

const only = arg('city')
if (only && !CITIES.includes(only)) {
  console.error(`Unknown city "${only}". Known: ${CITIES.join(', ')}`)
  process.exit(1)
}
for (const city of only ? [only] : CITIES) build(city)
